In [1]:
"""
Preamble for most code and jupyter notebooks
@author: bridgetsmart
@notebook date: 8 Sep 2023
"""

import numpy as np, pandas as pd

import matplotlib.pyplot as plt, seaborn as sns
import matplotlib as mpl

import math, string, re, pickle, json, time, os, sys, datetime, itertools

from tqdm.notebook import tqdm

In [2]:
# load in Ukraine Russia data
with open('full_hashtag_data_sentiments_matched_bot_class.pkl','rb') as f:
    df = pickle.load(f)

In [33]:
# sort by mean bot classification probability and then count
d_temp = df[~df.BotClassificationP.isna()].groupby('author_id').agg({'BotClassificationP':['mean','count']})

# filter to get counts only larger than 200
d_temp = d_temp[d_temp[('BotClassificationP','count')] > 200]
d_temp.sort_values([('BotClassificationP','mean'), ('BotClassificationP','count')],ascending=[True, False])

# df.groupby('author_id').agg({'BotClassificationP':['mean','count']}).sort_values(('BotClassificationP','mean'),ascending=False)

                    BotClassificationP
                                  mean count
author_id
2889262156                    0.306188   475
2652298388                    0.391216   359
2469228290                    0.419722   378
751525449541582848            0.419722   345
2742542732                    0.419722   216
...                                ...   ...
1448298903216984066           0.923535   495
1256088677375258625           0.923535   271
760694335356690432            0.923535   358
2359337692                    0.930754   248
1037028403734446080           1.000000   253

[142 rows x 2 columns]

In [ ]:
Bot = '1037028403734446080'
N_bot = 253
NotBot = '2889262156'
N_NotBot = 475